title = "ntoofu"
theme = "manis"
enableGitInfo = true

# Use GitHub Pages
baseURL = "https://ntoofu.github.io/blog/"
publishDir = "docs"
canonifyURLs = true

# Copyright notice. Note: You can use HTML tag here
copyright = "&copy; 2018 ntoofu"
pluralizeListTitles = false

# Minimum number of posts before paginate navigation show up
paginate = 20

# Your disqus shortname
# disqusShortname = ""

# Edit this if you want to translate your blog
defaultContentLanguage = "en"

# Code Highlighting (Chroma)
pygmentsCodeFences = true
pygmentsUseClasses = true

[taxonomies]
	tag = "tags"

[params]
	# If false, use minified CSS (ui.min.css)
	debugCSS = false
	# Custom CSS
	customCSS = []
	
	# List of sections support disqus comments
    # disqusSections = [ "blog" ]
	disqusSections = []
	# Site meta description
	description = "ntoofuの技術ブログ"
	# Site's Tagline (Subtitle or Keyword)
	tagline = "ntoofuの技術ブログ"
	# If true give attribution to this theme
	themeAttrib = true
	# URL to license file, can be outside of your domain
    # licenseURL = "/about/license"

	# Configure which section for Latest Posts
	postSection = "post"
	# Configure which section for Latest Works
	workSection = "work"

	# 404 Configuration
	head404 = "Sorry, I can't find what you want."
	sub404 = "Back to <a href='/'>Home</a>."

	# Color of your website's accent
	colorTheme = "#2c6be0"
	# Maximum number of item in Latest Posts or Works
	latestCount = 5
	# Path to site's favicon image
	faviconImg = ""
	# Date format in item list
	dateFmt = "2006-01-02"

	# Code Highlighting (HighlightJS)
	highlightJs = false
	highlightJsLanguages = [ "go" ]
	highlightJsStyle = "ocean"

	# Social Links
    # email = ""
	github = "https://github.com/ntoofu/"
	twitter = "https://twitter.com/ntoofu"

[frontmatter]
	date = [":filename", "date", ":default"]
	lastmod = ["lastmod", ":git", ":fileModTime", ":default"]
